#cloud-config
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [recurse_array]

users:
  - name: torsten
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGY2GZU19neGfVAVuIOKt0iIMKUDDz0H72dPROsVPFen

packages:
  - unattended-upgrades
  - apt-listchanges
  - apt-transport-https
  - gnupg-agent
  - gnupg
  - ca-certificates
  - lsb-release
  - curl
  - jq
  - joe

write_files:
  - path: /etc/ssh/sshd_config
    owner: root:root
    permissions: '0644'
    content: |
      PermitRootLogin no
      PasswordAuthentication no
      ChallengeResponseAuthentication no
      UsePAM yes
      AllowAgentForwarding yes
      AllowTcpForwarding yes
      X11Forwarding no
      PrintMotd no
      AcceptEnv LANG LC_* EDITOR
      Subsystem sftp	/usr/lib/openssh/sftp-server

runcmd:
  # Install doctl
  - curl -sfLo /tmp/doctl.tar.gz https://github.com/digitalocean/doctl/releases/download/v1.69.0/doctl-1.69.0-linux-amd64.tar.gz
  - tar xzvf /tmp/doctl.tar.gz -C /usr/local/bin/
  - chmod 755 /usr/local/bin/doctl
