#cloud-config
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [recurse_array]

write_files:
%{ for cert in tls_certs }
  - path: /etc/certs/tls-cert-${cert.name}.key
    owner: root:root
    content: |
      ${indent(6, cert.private_key_pem)}
  - path: /etc/certs/tls-cert-${cert.name}.crt
    owner: root:root
    content: |
      ${indent(6, cert.certificate_pem)}
  - path: /etc/certs/tls-cert-${cert.name}.pem
    owner: root:root
    content: |
      ${indent(6, cert.certificate_pem)}
      ${indent(6, cert.issuer_pem)}
%{ endfor }

  - path: /etc/nginx/conf.d/default.conf
    owner: root:root
    content: |
      server {
          listen 80 default_server;
          listen [::]:80 default_server;

          location / {
              return 301 https://$host$request_uri;
          }
      }

runcmd:
  # install mainline nginx
  - echo "deb http://nginx.org/packages/debian `lsb_release -cs` nginx" > /etc/apt/sources.list.d/nginx.list
  - curl -fsSL https://nginx.org/keys/nginx_signing.key | apt-key add -
  - apt-get update
  - apt -q -y -o Dpkg::Options::=--force-confdef install nginx

  # launch nginx
  - curl -sfL https://ssl-config.mozilla.org/ffdhe4096.txt > /etc/nginx/dhparam.pem
  - systemctl enable nginx
  - systemctl start nginx
