#cloud-config
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [recurse_array]

write_files:
  - path: /etc/nginx/conf.d/default-tls-simple.conf
    owner: root:root
    content: |
      server {
          listen 443 ssl;

          ssl_certificate     /etc/certs/tls-cert.crt;
          ssl_certificate_key /etc/certs/tls-cert.key;
      }
