#cloud-config
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [recurse_array]

write_files:
  - path: /etc/nginx/conf.d/default-tls-broken.conf
    owner: root:root
    content: |
      server {
          listen 443 ssl;

          ssl_certificate     /etc/certs/tls-cert-rsa2048.crt;
          ssl_certificate_key /etc/certs/tls-cert-rsa2048.key;
      }
  - path: /etc/nginx/conf.d/default-tls-rsa2048.conf
    owner: root:root
    content: |
      server {
          listen 444 ssl;

          ssl_certificate     /etc/certs/tls-cert-rsa2048.pem;
          ssl_certificate_key /etc/certs/tls-cert-rsa2048.key;
      }
  - path: /etc/nginx/conf.d/default-tls-rsa4096.conf
    owner: root:root
    content: |
      server {
          listen 445 ssl;

          ssl_certificate     /etc/certs/tls-cert-rsa4096.pem;
          ssl_certificate_key /etc/certs/tls-cert-rsa4096.key;
      }
  - path: /etc/nginx/conf.d/default-tls-ecdsa.conf
    owner: root:root
    content: |
      server {
          listen 446 ssl;

          ssl_certificate     /etc/certs/tls-cert-ecdsa.pem;
          ssl_certificate_key /etc/certs/tls-cert-ecdsa.key;
      }

  - path: /etc/nginx/conf.d/default-tls-ecdsa-ocsp.conf
    owner: root:root
    content: |
      server {
          listen 447 ssl;

          ssl_certificate     /etc/certs/tls-cert-ecdsa.pem;
          ssl_certificate_key /etc/certs/tls-cert-ecdsa.key;

          # OCSP stapling
          ssl_stapling on;
          ssl_stapling_verify on;
      }
  - path: /etc/nginx/conf.d/default-tls-ecdsa-ocsp-sessions.conf
    owner: root:root
    content: |
      server {
          listen 447 ssl;

          ssl_certificate     /etc/certs/tls-cert-ecdsa.pem;
          ssl_certificate_key /etc/certs/tls-cert-ecdsa.key;
          ssl_session_timeout 1d;
          ssl_session_cache shared:MozSSL:10m;
          ssl_session_tickets off;
          ssl_stapling on;
          ssl_stapling_verify on;
      }
