---
- name: Provision a basic http system
  hosts: tls
  become: true
  tasks:
    - name: apply security updates
      shell: yum -y update

    - name: install base software
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - openssl
        - nginx
        - haproxy
        - gcc
        - pcre-devel 
        - openssl-devel
        
    - include: includes/compile-haproxy.yml

    - name: download certbot installer
      get_url: 
        url: "https://dl.eff.org/certbot-auto"
        dest: "/usr/bin/certbot"
        mode: 0755
    
    - name: create certbot configuration directory
      file:
        name: /etc/letsencrypt
        state: directory
     
    - name: configure certbot
      copy:
        src: letsencrypt/cli.ini
        dest: /etc/letsencrypt/cli.ini
     
      # this might not be as scriptable as it should be. Call
      # manually on errors :-(
    - name: install certbot & friends 
      shell: /usr/bin/certbot --text --version --debug
    
    - name: configure nginx localhost site
      copy:
        src: nginx/localhost.conf
        dest: /etc/nginx/conf.d/localhost.conf

    - name: configure nginx
      copy:
        src: nginx/nginx.conf
        dest: /etc/nginx/nginx.conf
        force: true
        validate: 'nginx -t -c %s'
    
    - name: start nginx
      service:
        name: nginx
        state: restarted
        enabled: true

    - name: configure haproxy
      template: 
        src: haproxy/simple.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        force: true
        validate: 'haproxy -c -f %s'
    
    - name: start haproxy
      service:
        name: haproxy
        state: restarted
        enabled: true