---
- name: Enable tls in haproxy
  hosts: tls
  become: true
  
  tasks:
    - name: configure haproxy to use tls
      copy:
        src: haproxy/tls-simple.cfg
        dest: /etc/haproxy/haproxy.cfg
        force: true
        validate: 'haproxy -c -f %s'

    - name: restart haproxy
      service:
        name: haproxy
        state: restarted
