---
- name: Speedup ttfb in tls mode
  hosts: tls
  become: true
  
  tasks:
    - name: provide ocsp stapling information
      shell: >
        openssl ocsp -noverify 
        -issuer /etc/ssl/certs/{{ domain }}.intermediate.crt
        -cert /etc/ssl/certs/{{ domain }}.pem
        -url http://ocsp.int-x1.letsencrypt.org \
        -header "HOST" "ocsp.int-x1.letsencrypt.org" \
        -respout /etc/ssl/certs/{{ domain }}.pem.ocsp
  
    - name: configure haproxy to use tls
      copy:
        src: haproxy/tls-ttfb-tuned.cfg
        dest: /etc/haproxy/haproxy.cfg
        force: true
        validate: 'haproxy -c -f %s'

    - name: restart haproxy
      service:
        name: haproxy
        state: restarted
