---
- name: Enable http2
  hosts: tls
  become: true
  
  tasks:
    - name: configure haproxy to negotiate h2 in alpn
      copy:
        src: haproxy/tls-http2.cfg
        dest: /etc/haproxy/haproxy.cfg
        force: true
        validate: 'haproxy -c -f %s'
        
    - name: configure nginx localhost site
      copy:
        src: nginx/localhost-http2.conf
        dest: /etc/nginx/conf.d/localhost.conf
    
    - name: restart nginx
      service:
        name: nginx
        state: restarted

    - name: restart haproxy
      service:
        name: haproxy
        state: restarted
